pull_request_rules:
  - name: automatically merge Scala Steward PRs on CI success
    conditions:
      - or:
        - author=github-actions[bot]
        - author=scala-steward
        - author=majk-p
      - status-success~=Build and Test
      - body~=labels:(.*semver-patch.*)|(.*semver-spec-patch.*)
    actions:
      merge:
        method: merge
